-- Initialize triggers

-- Trigger for EMPLOYEE_SEQ
CREATE OR REPLACE TRIGGER EMPLOYEE_TRIGGER
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    BEGIN
        SELECT EMPLOYEE_SEQ.NEXTVAL INTO :new.P_ID FROM Dual;
    END;
/

-- Trigger for REIMBURSEMENT_FORMS_SEQ
CREATE OR REPLACE TRIGGER REIMBURSEMENT_FORMS_TRIGGER
    BEFORE INSERT ON REIMBURSEMENT_FORMS
    FOR EACH ROW
    BEGIN
        SELECT REIMBURSEMENT_FORMS_SEQ.NEXTVAL INTO :new.F_ID FROM Dual;
    END;
/

-- Trigger for REQUEST_INFORMATION_SEQ
CREATE OR REPLACE TRIGGER REQUEST_INFORMATION_TRIGGER
    BEFORE INSERT ON REQUEST_INFORMATION
    FOR EACH ROW
    BEGIN
        SELECT REQUEST_INFORMATION_SEQ.NEXTVAL INTO :new.R_ID FROM Dual;
    END;
/

-- Trigger for TRANSACTION_LOG_SEQ
CREATE OR REPLACE TRIGGER TRANSACTION_LOG_TRIGGER
    BEFORE INSERT ON TRANSACTION_LOG
    FOR EACH ROW
    BEGIN
        SELECT TRANSACTION_LOG_SEQ.NEXTVAL INTO :new.LOG_ID FROM Dual;
    END;
/