-- Initialize sequences

-- Sequence for P_IDs in the EMPLOYEE table
CREATE SEQUENCE EMPLOYEE_SEQ
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;
    
-- Sequence for F_IDs in the REIMBURSEMENT_FORMS table
CREATE SEQUENCE REIMBURSEMENT_FORMS_SEQ
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;

-- Sequence for R_IDs in the REQUEST_INFORMATION table
CREATE SEQUENCE REQUEST_INFORMATION_SEQ
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;

-- Sequence for STATUS_IDs in the APPLICATION_STATUS table
CREATE SEQUENCE APPLICATION_STATUS_SEQ    
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;
    
-- Sequence for LOG_IDs in the TRANSACTION_LOG table
CREATE SEQUENCE TRANSACTION_LOG_SEQ
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;
